apiVersion: apps/v1
kind: Deployment
metadata:
  name: logiai-backend
  namespace: logiai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logiai-backend
  template:
    metadata:
      labels:
        app: logiai-backend
    spec:
      containers:
      - name: backend
        image: BACKEND_ECR_URL:latest   # replaced by CI/CD
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: logiai-secrets
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
