apiVersion: apps/v1
kind: Deployment
metadata:
  name: logiai-frontend
  namespace: logiai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logiai-frontend
  template:
    metadata:
      labels:
        app: logiai-frontend
    spec:
      containers:
      - name: frontend
        image: FRONTEND_ECR_URL:latest   # replaced by CI/CD
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
